### PR TITLE
Add folding ranges

### PR DESCRIPTION
**Pull request by i-am-the-slime**
# What?
This adds a folding range for imports (that means it's possible to "hide/show" all imports with the little caret left of the line or a command).

# Why?
This extension is already really good at managing imports and I'm more than happy to delegate this 💩 to a computer. However, the structure of PureScript programs requires imports to be one of the first things one sees when opening a file. Being able to automatically hide them mitigates this problem.

# How?
It is quite naïvely implemented (it goes from the first line that starts with `import ` until the last that does).

# Misc
I also updated some dependencies.
Note that this change is on top of my PR that ports to spago.

### CODE REVIEW

**Comment by i-am-the-slime** [comment]
folding
Here's an example  of how it looks.

**Comment by nwolverson** [comment]
This will be not-folded by default right?

**Comment by i-am-the-slime** [comment]
No. There is a plugin needed for this in VSCode. I think there's even an issue for it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by i-am-the-slime** [comment]
Essentially what it does is provide which ranges the user *could* fold/unfold (where to add a [rotating triangle](https://superuser.com/questions/638139/whats-the-proper-name-of-that-symbol-to-collapse-expand-nodes-in-a-directory-tr)) and how much will be shown/revealed when it's clicked).

**Pull request merged**
