### PR TITLE
Support type applications with language-cst-parser@v0.14.0

### LINKED ISSUE #204: Presence of VTA prevents LSP functionality
```purescript
module M where
import Prelude

id :: forall @a. a -> a
id x = let _ = map in x

foo :: String -> String
foo = id @String -- if VTA is present, hovering on `map` above doesn't work. when it's removed, it does
```

### PR DESCRIPTION
**Pull request by jmatsushita**
Fixes #204

### CODE REVIEW

**Comment by jmatsushita** [comment]
Seems that type application syntax was added in [purescript-language-cst-parser `v0.13.0`](https://github.com/natefaubion/purescript-language-cst-parser/releases/tag/v0.13.0)

**Comment by jmatsushita** [comment]
This will also probably require to upgrade the `vscode-ide-purescript` dependencies in [packages.dhall](https://github.com/nwolverson/vscode-ide-purescript/blob/main/packages.dhall#L79) as well as [in the `package.json`](https://github.com/nwolverson/vscode-ide-purescript/blob/main/package.json#L365)

**Comment by nwolverson** [comment]
Thanks, missed this, it seems amazing the change is so simple to bring in :)

**Comment by jmatsushita** [comment]
> it seems amazing the change is so simple to bring in :)

Yes! So satisfying ☺️ Solid shoulders we stand on 💪

**Pull request merged**
