### PR TITLE
Add more documentation for CoC/Vim setup

### PR DESCRIPTION
**Pull request by andywhite37**
Hello! Thanks for all the work you've put into this project. I spent some time this evening setting it up with CoC/nvim, and was able to get it working. I'm relatively new to the CoC ecosystem, so it took a little fumbling around to get the code formatting working. I wondered if you'd be interested in this little bit of extra documentation to help the next person who comes along? It's arguable if this more detailed info belongs here or more in the CoC documentation, so no worries if you don't want to include this here at this time. It's also possible that I've done something wrong or missed something with my setup, so corrections are welcome.

### CODE REVIEW

**Comment by nwolverson** [comment]
Not sure what the best level of detail is that makes it easier to understand but also find the other editor text etc - I think for now we can include everything and if it is too much, can always pull it out somewhere else and link the extra info.

One thing, there is some generic text about purty, I think that should be dragged to the very top as it is not specific - maybe just under usage

**Comment by andywhite37** [comment]
Makes sense - I'll update my PR tonight hopefully. Thanks!

**Comment by andywhite37** [comment]
@nwolverson I updated my PR to move the `purty` info up to the top under general usage. Let me know what you think, I'd be happy to make any other changes.

**Comment by nwolverson** [comment]
Thanks!

**Comment by andys8** [comment]
Thanks for this PR @andywhite37

**Pull request merged**
