### PR TITLE
Formatting Provider using `purty`

### LINKED ISSUE #61: Code formatting
[haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) proposes to format the code via [brittany](https://github.com/lspitzner/brittany). It would be possible to do the same for eg. with [purty](https://gitlab.com/joneshf/purty)?

### PR DESCRIPTION
**Pull request by andys8**
Adding a formatting provider that is using [`purty`](https://gitlab.com/joneshf/purty).

## Issues

Closes #61 

## What this PR does not

* Handle what happens when `purty` is not installed or found
* Handle `purty` would fail

### CODE REVIEW

**Comment by nwolverson** [comment]
Cool! thanks for the pr. 

I'll give it a go when I can.

Thoughts so far (none of which should block the PR):

* I believe `purty` is npm installable, I guess we should respect the "npm path" config (as for `purs` where npm bin is added to the `PATH`)
* Possibly explicit path option, if all other executables we're currently calling have that

**Comment by andys8** [comment]
That's interesting. We could also include `purs` via `package.json`. But I think there might be a good amount of users using binaries or [nix](https://github.com/justinwoo/easy-purescript-nix/blob/master/purty.nix). So relying on `npm path` or fixing the version by including it could lead to trouble for them.

Feel free to extend the PR, especially in regards to setup, forking the process and error handling :)

**Comment by andys8** [comment]
> purty not installed - Takes down the entire language server

I saw an error in the logs, but the language server didn't stop working for me. Nonetheless, I rebased and added a commit to basically ignore this case.

**Comment by andys8** [comment]
> Observed some duplication at the end of the file when the reformat is making the text shorter, I think the edit needs tweaked

Couldn't reproduce it. Do you have an example? If something is wrong in that regard, it's likely here: https://github.com/nwolverson/purescript-language-server/pull/83/files#diff-dd1de01859b83f76b0f93154c019d29fR48

**Comment by nwolverson** [comment]
I am still looking at this, I'll push a fix or merge this and fix

The "taking down language server" - I think this is an issue when the language server is launched for vscode specifically, it's an Electron not node process, writing to the stream of the forked process is instantly causing the process to quit, instead of getting some exception that gets captured in our `Aff` stuff.

**Comment by nwolverson** [comment]
I am still looking at this, I'll push a fix or merge this and fix

The "taking down language server" - I think this is an issue when the language server is launched for vscode specifically, it's an Electron not node process, writing to the stream of the forked process is instantly causing the process to quit, instead of getting some exception that gets captured in our `Aff` stuff.

**Comment by nwolverson** [comment]
I am still looking at this, I'll push a fix or merge this and fix

The "taking down language server" - I think this is an issue when the language server is launched for vscode specifically, it's an Electron not node process, writing to the stream of the forked process is instantly causing the process to quit, instead of getting some exception that gets captured in our `Aff` stuff.

**Comment by nwolverson** [comment]
I've reworked this by stealing code from the `purs` exec, seems over complicated and can no doubt be improved by using some other API but it does avoid the process exit that I saw above.

That code does mean that we have the npm path inclusion (according to settings) for this too.

**Comment by andys8** [comment]
That's awesome

**Pull request merged**
